### ISSUE TITLE
Verfikasi rampungan: tombol selesai hanya bisa setelah punya spd

### ISSUE THREAD

**Issue by vatoer** [pirsani/panda#18]

**Comment by pirsani** [comment]
This issue has been migrated to pirsani/strasa as issue #63

**Comment by pirsani** [comment]
This issue has been migrated to pirsani/strasa as issue #18

**Comment by pirsani** [comment]
This issue has been migrated to pirsani/strasa as issue #18

**Comment by pirsani** [comment]
This issue has been migrated to pirsani/strasa as issue #18

**Comment by pirsani** [comment]
This issue has been migrated to pirsani/strasa as issue #18

**Comment by pirsani** [comment]
This issue has been migrated to pirsani/strasa as issue #18

**Comment by pirsani** [comment]
This issue has been migrated to pirsani/strasa as issue #18
